version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fourteenvoices-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      # Skip migrations on startup to avoid ESM issues
      SKIP_MIGRATIONS: 'true'
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      # Basic Traefik labels
      - 'traefik.enable=true'
      - 'traefik.http.routers.fourteenvoices.rule=Host(`14voices.fromjasp.com`)'
      - 'traefik.http.routers.fourteenvoices.entrypoints=websecure'
      - 'traefik.http.routers.fourteenvoices.tls.certresolver=letsencrypt'
      - 'traefik.http.services.fourteenvoices.loadbalancer.server.port=3000'
